### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by gianlucastella1** [Seitenbau/RoomieReloaded#23]
8 years ago I built a web application with the same goal as your RoomieReloaded (simple HTML page hosted by zimbra itself, with js calling the calendar API and displaying the results)

I came to your repo looking for a replacement for my app, since it cannot display recurring events (they are becoming very popular in our company).

Looking at your code, I found out that ZimbraAdapter access calendar data via [Get Calendar API](https://wiki.zimbra.com/wiki/Zimbra_REST_API_Reference:Get_Calendar), as I did using json format.
As far as I understood, the only way to access recurring events' occurrences with this API is:
- start & end parameters must include the first occurrence of the event
- you need to parse recurrence information and find if an occurence occures in the time frame you are displaying

Since we don't know the date of the first occurrence (and we don't want to overload the system loading 3 years old events), how did you manage this?

I spent many hours on this subject, without being able to find a way to retrieve the expanded calendar (only provided using HTML format)...

**Comment by th1723** [comment]
Dear Gianluca,

its been a while since we implemented this, but if I remember correctly, Zimbra actually does the heavy lifting. In ZimbraAdapter.cs line 34 we build a url like this:
` var url = $"{baseUrl}/{room}?fmt=ics&start={startString}&end={endString}&auth=ba";`
Zimbra returns all the data required to find the appointments in the specified timeframe, including recurring appointments. The special thing about this is, that a reccuring event will have the begin of the very first appointment as start along with some information about the recuring type, like weekly at monday or every tenth of the month. You then have to calculate the actual occurences yourselve and pick those you need, but you can be sure that there will be occurences in the provided time frame.

Now, you can see that we use `ics` as format. Generally we like to work with json data, too, but here it has a clear disadvantage: The json datastructure is totally nuts and no one understands it :D
The ics data on the other hand is well known and for most programming languages, you will find some library that can parse this data and thats exactly what we do with the ics string in CalendarService.cs line 26 with:
`var calendar = Ical.Net.Calendar.Load(icsCalendar);`

So, we delegate this to the Ical.Net package. You can find it here on github or as a nuget package, but if you're using another programming language, you would have to search for a similar library ... or do it all yourself.

Hope that helps and kind regards
th1723

**Comment by MaxAtoms** [comment]
@gianlucastella1 I'm closing this issue for now.
If you have further questions, feel free to add a comment to this issue or open another one.
